=== JuanmaLobato98/LMSGI/XML/actividad5_16/Ejercicio1/esquemacomunidad.xsd
<?xml version = "1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">


    <xs:element name="comunidad" type="tComunidad"/>
    <xs:complexType name="tComunidad">
        <xs:sequence>
            <xs:element name="vecino" type="tVecino"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tVecino">
        <xs:all>
            <xs:element name="codigo" type="xs:integer"/>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellidos" type="xs:string"/>
            <xs:element name="portal" type="xs:string"/>
            <xs:element name="pisoyletra" type="xs:string"/>
            <xs:element name="cuenta" type="tCuenta"/>
            <xs:element name="cargo" type="tCargo"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="tCuenta">
        <xs:restriction base="xs:string">
            <xs:maxLength value="20"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tCargo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Presidente"></xs:enumeration>
            <xs:enumeration value="Vicepresidente"></xs:enumeration>
            <xs:enumeration value="Vocal"></xs:enumeration>
            <xs:enumeration value="Ninguno"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== JuanmaLobato98/LMSGI/XML/actividad5_16/Ejercicio1/comunidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<comunidad xmlns:xs="https://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="esquemacomunidad.xsd">
    <vecino>
        <codigo>1</codigo>
        <nombre>Juan</nombre>
        <apellidos>Fernandez</apellidos>
        <portal>4</portal>
        <pisoyletra>12A</pisoyletra>
        <cuenta>12345678901234567890</cuenta>
        <cargo>Presidente</cargo>
    </vecino>
    <vecino>
        <codigo>2</codigo>
        <nombre>Maria</nombre>
        <apellidos>Lopez</apellidos>
        <portal>2</portal>
        <pisoyletra>1A</pisoyletra>
        <cuenta>12345678901234567890</cuenta>
        <cargo>Vicepresidenta</cargo>
    </vecino>
    <vecino>
        <codigo>3</codigo>
        <nombre>Jose</nombre>
        <apellidos>Miranda</apellidos>
        <portal>4</portal>
        <pisoyletra>3B</pisoyletra>
        <cuenta>12345678901234567890</cuenta>
        <cargo>Ninguno</cargo>
    </vecino>
    <vecino>
        <codigo>4</codigo>
        <nombre>Jorge</nombre>
        <apellidos>Garcia</apellidos>
        <portal>4</portal>
        <pisoyletra>5C</pisoyletra>
        <cuenta>12345678901234567890</cuenta>
        <cargo>Vocal</cargo>
    </vecino>
</comunidad>
