=== JuanmaLobato98/LMSGI/XML/actividad5_16/Ejercicio2/esquemaconcesionario.xsd
<?xml version = "1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">


    <xs:element name="concesionario" type="tConcesionario"/>
    <xs:complexType name="tConcesionario">
        <xs:sequence>
            <xs:element name="coche" type="tCoche"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tCoche">
        <xs:all>
            <xs:element name="codigo" type="xs:integer"/>
            <xs:element name="marca" type="xs:string"/>
            <xs:element name="modelo" type="xs:string"/>
            <xs:element name="matricula" type="xs:string"/>
            <xs:element name="matriculacion" type="tMatriculacion"/>
            <xs:element name="potencia" type="xs:integer"/>
            <xs:element name="plazas" type="xs:integer"/>
            <xs:element name="puertas" type="tPuertas"/>
        </xs:all>
    </xs:complexType>

    <xs:simpleType name="tMatriculacion">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="2000"></xs:minExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tPuertas">
        <xs:restriction base="xs:integer">
            <xs:enumeration value="2"></xs:enumeration>
            <xs:enumeration value="3"></xs:enumeration>
            <xs:enumeration value="4"></xs:enumeration>
            <xs:enumeration value="5"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== JuanmaLobato98/LMSGI/XML/actividad5_16/Ejercicio2/concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<concesionario xmlns:xs="https://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="esquemaconcesionario.xsd">
<coche>
    <codigo>1</codigo>
    <marca>Seat</marca>
    <modelo>Leon</modelo>
    <matricula>3231JFC</matricula>
    <matriculacion>2018</matriculacion>
    <potencia>110</potencia>
    <plazas>5</plazas>
    <puertas>5</puertas>
</coche>
<coche>
    <codigo>2</codigo>
    <marca>Mitshubishi</marca>
    <modelo>Montero</modelo>
    <matricula>8530DHD</matricula>
    <matriculacion>2005</matriculacion>
    <potencia>115</potencia>
    <plazas>5</plazas>
    <puertas>5</puertas>
</coche>
<coche>
    <codigo>3</codigo>
    <marca>Hyundai</marca>
    <modelo>i30</modelo>
    <matricula>4298HJX</matricula>
    <matriculacion>2012</matriculacion>
    <potencia>90</potencia>
    <plazas>5</plazas>
    <puertas>5</puertas>
</coche>
<coche>
    <codigo>4</codigo>
    <marca>Ford</marca>
    <modelo>Puma</modelo>
    <matricula>1234ABC</matricula>
    <matriculacion>2022</matriculacion>
    <potencia>160</potencia>
    <plazas>5</plazas>
    <puertas>4</puertas>
</coche>
</concesionario>
