<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bebidas [
 <!ELEMENT bebidas (bebida)*>
 <!ELEMENT bebida ((codigo | nombre), precio)>
 <!ELEMENT codigo (#PCDATA)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT precio (#PCDATA)>
]>
<bebidas>
    <bebida>
       <codigo>L45</codigo> <!-- Aqui sobraba o codigo o nombre ya que no puedecontener los dos-->
       <precio>8</precio>
    </bebida>
    <bebida>
       <nombre>x</nombre> <!-- Aqui faltaba una etiqueta codigo o nombre-->
       <precio>6</precio>
    </bebida>
 </bebidas>